### ISSUE TITLE
Disposition-Notification-Options used in 2 different ways

### ISSUE THREAD

**Issue by LowerWolves** [tiamo/phpas2#12]
I am deep into the code:
On the sending side, the Disposition-Notification-Options are included in the **message** headers, but on the receiving side, they are only parsed from the **payload** headers. Therefore, the "micAlgo" variable is never given a value, but the micContent variable is not empty, causing an exception in CryptoHelper::calculateMIC.
BTW, I have never posted in GitHub before, so my apologies if this is not the right forum for my comment.

**Comment by tiamo** [comment]
fixed 1.3.6
