### ISSUE TITLE
Conflicting with guzzlehttp/guzzle ^7

### ISSUE THREAD

**Issue by ClausScherschel** [tiamo/phpas2#14]
Would be great, if the dependency on guzzle could be uped to or include guzzlehttp/guzzle ^7.0 as there might be locked packages requiring new versions of that lib.

**Comment by tiamo** [comment]
This version of "guzzle" does not support php 5.6

**Comment by mackieee** [comment]
@tiamo Hey Tiamo, Love the work you've done by the way! :) 

What current aspects of the code would fail above PHP 7.2? I can see you're very aware of this from your other projects that 5.6 has far surpassed the EOF timeline. I can see this has passed the CI builds against those higher PHP versions.

**Comment by tiamo** [comment]
@MackieeE Thanks!
The library correctly works with php 7+
Unfortunately many people still use php 5.6

**Comment by tiamo** [comment]
@ClausScherschel I've released 1.4.3 with guzzle: ^7.0 support

**Comment by ClausScherschel** [comment]
@tiamo Woah, that great news, thanks a lot!
