### ISSUE TITLE
headers of body are sent instead of headers of message

### ISSUE THREAD

**Issue by voserwin** [tiamo/phpas2#2]
I needed to change Management.php line 221 with the lines from former version to make it work:
'headers' => MimePart::fromString($message->getHeaders())->getHeaders(),
                'body' => $message->getPayload(),

in latest version it is passing the headers of the payload.
I am wondering why you changed this?

**Comment by Hordelo** [comment]
Hey,
i know my comment doesnt belong to your question or comment at all but i am struggling with the plugin myself at the moment. It looks like you made it work.
I cant get it to work for the past days... i did set it up all correctly (in my opinion). Unfortunately it doesnt send a message.
I get the StatusCode 200 from sendMessage() but i dont receive anything at the targetURL.

Are you able to share your code with me somehow?
Would appreciate it a lot

greetings

**Comment by voserwin** [comment]
Hey Hordelo,

Maybe we can work together on this, because i also still not got it running
and also in big need it for it for a project.
When i fixed several bugs I still got sha256-errors.

Since the last suggestion, let me first try again on PHP7.3. I was still
trying to get it going on PHP5.5
Last weekend I installed higher php version.

I will share my improvements by creating a fork next sunday Oct-28.
I at least could send messages to the other side.
Maybe you can give it a try and I hope you have a better understanding on
hashing and encoding.

Let's keep in touch,
Erwin


Op di 23 okt. 2018 om 11:57 schreef Hordelo <notifications@github.com>:

**Comment by Hordelo** [comment]
Hey,

sorry had some other projects before this... Didnt have much time for it.
Atleast i am now able to send a message out. I unfortunately dont know how to test receiving a message on my side (if you have any help or sites to do this, would be awesome)

Otherwise did you fix your errors? I only got a sha-error in the beginning. Somehow its not showing up anymore.

Do you know how to add a file, if its possible?
Greetings

**Comment by voserwin** [comment]
1. The demo example is outdated, I figured out.
Pass the **build**-message to send function.
$buildmessage = $manager->buildMessage($message);
$manager->sendMessage($buildmessage);
2. Furthermore change encoding of message hardcoded in library to 'base64'. (not sure why I needed to change this, but receiver is checking on base64 encoding.

What to use as receiver? the same library! but than reception side:
So for example I used Laravel. Create a route to a function that does following:
$response = $server->excecute($request);

Use this route as url when initializing both partners.
This url can be localhost within same project.
As further test, now upload the project to a server with a real domain name and start testing from localhost to server. Run the init-function once at server as well.
For me it is working fine.

Validating is done by checking what files you receive in storage folder.
Also make sure you create a logger-instance (the lib has build-in log-functionality)


General remark: I also needed to completely debug the lib to make it work. A good working example would really make live lots easier.

**Comment by Hordelo** [comment]
I really start to hate this S***  :D

Is there maybe a chance that you can upload your code?
If you still have your test code somewhere in the back

**Comment by Hordelo** [comment]
ok... a long day full of as2... but finally got it to work the way i need it...

**Comment by voserwin** [comment]
Ok, congrats.
welcome to the club!

Op di 20 nov. 2018 om 15:59 schreef Hordelo <notifications@github.com>:

**Comment by Hordelo** [comment]
i have one more question, maybe you already have an answer for it :D

I need to the ServerResponse. I tried it with some functions but they didnt really do what i need...
All i need is the StatusCode and the ResponseAnswer basically.

Do you have anything useful?
