### ISSUE TITLE
How to edit the signature algorithm from sha256 to sha1

### ISSUE THREAD

**Issue by onlineware** [tiamo/phpas2#27]
Hello,

how can i change the signature algorithm? The changes in the config/partners.php file were not successful. I also edit the mdn_options in this file. In the error log always show me the following error: app.CRITICAL: (MIC) Invalid hash algorithm. The partner send an test file with "sha1". 

What am I doing wrong?

Thanks in advance

**Comment by tiamo** [comment]
Hi @onlineware,

need more details )
