### ISSUE TITLE
MDN coming with LF instead of CR/LF

### ISSUE THREAD

**Issue by ClausScherschel** [tiamo/phpas2#33]
Hey,
we are receiving complaints, that returned MDNs are buggy, because most probably there are only LFs instead of CR/LFs as with previous versions. This seems to put original sender into trouble evaluating our response. There seems to be no option configuring this, right?

Best regards,
Claus.

**Comment by robsonala** [comment]
Hi Claus, 
I have modified the setBody in some point due problem of limitation of preg_replace (I was hadling really big files)
I didn't have any complaining though. You can try revert this commit and check if it works for you
https://github.com/tiamo/phpas2/commit/5e3f63430310a3de4438dc55f7e0e448171903f8

thanks,
R.
