### ISSUE TITLE
Problem with the encoding special german characters

### ISSUE THREAD

**Issue by dr-roshyara** [tiamo/phpas2#37]
Hi , 
I have problem  when I send  send message with special german characters like ä ü ö etc. 
When I send the message containing these characters, the message is not encoded correctly. Where exactly I use  the option mentioning utf-8 format. I tried many ways but still the other party is getting the message not correctly. 
Kindest regards
Nab

**Comment by tiamo** [comment]
Hi @dr-roshyara! Could you show me an example of your code ?
