### ISSUE TITLE
Still "dev"/unstable?

### ISSUE THREAD

**Issue by wendelin** [tiamo/phpas2#4]
Currently one requirement is:
> "phpseclib/phpseclib": "dev-master"

This causes composer to raise a stink:
> tiamo/phpas2 1.3.1 requires phpseclib/phpseclib dev-master -> satisfiable by phpseclib/phpseclib[dev-master] but these conflict with your requirements or minimum-stability.

Any chance that the stable version of "phpseclib/phpseclib" could used instead?

If not could you add to the install docs that the following should be added:
>    "minimum-stability": "dev",
>    "prefer-stable": true,

Thanks

**Comment by tiamo** [comment]
fixed
