### ISSUE TITLE
Regression with psr/http-message 2.0

### ISSUE THREAD

**Issue by Guite** [tiamo/phpas2#41]
Upgrading `psr/http-message` to version 2.0 breaks `phpas2` because they added return types.

See https://github.com/php-fig/http-message/releases/tag/2.0

Error message:
```
Fatal error: Declaration of AS2\MimePart::getBody() must be compatible with Psr\Http\Message\MessageInterface::getBody(): Psr\Http\Message\StreamInterface in /builds/.../vendor/tiamo/phpas2/src/MimePart.php on line 308
```

**Comment by Guite** [comment]
I found a workaround in [this fork](https://github.com/khoosys/phpas2/tree/psr_version) which removed the PSR interfaces as part of [these commits](https://github.com/tiamo/phpas2/compare/master...khoosys:phpas2:psr_version).

**Comment by mattdinthehouse** [comment]
I had this issue too so I've forked and made a PR - #42
