### ISSUE TITLE
Receiving AS2 message from partner causes Entity `%s:%s` not found

### ISSUE THREAD

**Issue by ole1986** [tiamo/phpas2#8]
It seem that the check when receiving an AS2 message from the partner always causes an error that the entity has not been found given in  FileStorage.php on [line 125](https://github.com/tiamo/phpas2/blob/master/examples/models/FileStorage.php#L125)

So instead of calling `getMessage()` from the StorageInterface (see Server.php on [line 115](https://github.com/tiamo/phpas2/blob/master/src/Server.php#L115)) there should be a method `foundMessage()` to return either true or false and continue if the message has not been found.

**Comment by mackieee** [comment]
This from what I can tell will *always* be false upon first receive and throw an exception, same for true if it was there as a duplicate. 

Downgrading to 1.3.4 worked for me. I can't see where in 1.3.5 in the Server, where it *saves* the new incoming message before reading the contents - as it decides to read the message from the Storage, whereas in 1.3.4 it immediately reads it from the Request.

**Comment by tiamo** [comment]
fixed 1.3.6
